spring.application.name=risksrv3
server.port=8082
# next two lines/comments are setting for docker mongodb
# spring.data.mongodb.host=host.docker.internal
# spring.data.mongodb.port=27018
# next two lines/comments are setting for local mongodb service
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=riskdata
